import type {
  Character,
  Item,
  Stage,
  Weapon,
  WeatherEnemy,
} from "./types";

export const weatherEnemies: WeatherEnemy[] = [
  {
    id: "cloudy",
    index: "01",
    name: "曇り",
    maxHp: 240,
    color: "#b9c2c9",
    accentColor: "#63d8ff",
    coreColor: "#b7f2ff",
    icon: "☁",
    trait: "練習",
    threat: 2,
    difficulty: 1,
    description: "チュートリアル用の練習エネミー。視界を少し曇らせる。",
    playableInMvp: true,
  },
  {
    id: "heavyRain",
    index: "02",
    name: "豪雨",
    maxHp: 380,
    color: "#255f88",
    accentColor: "#29c8ff",
    coreColor: "#5ee7ff",
    icon: "☔",
    trait: "視界妨害",
    threat: 4,
    difficulty: 2,
    description: "強い雨で視界を妨げ、継続ダメージを与える。",
    playableInMvp: true,
  },
  {
    id: "thunderstorm",
    index: "03",
    name: "落雷",
    maxHp: 460,
    color: "#4b4f58",
    accentColor: "#ffd84d",
    coreColor: "#fff2a6",
    icon: "⚡",
    trait: "落雷",
    threat: 6,
    difficulty: 3,
    description: "周囲に落雷を発生させ、広範囲に高ダメージ。",
    playableInMvp: true,
  },
  {
    id: "tornado",
    index: "04",
    name: "竜巻",
    maxHp: 540,
    color: "#9fb8c8",
    accentColor: "#6be6ff",
    coreColor: "#8df0ff",
    icon: "◌",
    trait: "吸引",
    threat: 7,
    difficulty: 4,
    description: "プレイヤーを吸引し、接近して連続攻撃を行う。",
    playableInMvp: true,
  },
  {
    id: "rainySeason",
    index: "05",
    name: "梅雨",
    maxHp: 600,
    color: "#315d54",
    accentColor: "#4ce0b3",
    coreColor: "#8dffd8",
    icon: "♢",
    trait: "状態異常",
    threat: 7,
    difficulty: 4,
    description: "湿気をまとい、継続ダメージや移動速度低下を付与。",
    playableInMvp: true,
  },
  {
    id: "blizzard",
    index: "06",
    name: "吹雪",
    maxHp: 560,
    color: "#b7d7f2",
    accentColor: "#9fe8ff",
    coreColor: "#dff8ff",
    icon: "❄",
    trait: "凍結",
    threat: 6,
    difficulty: 3,
    description: "吹雪を起こし、氷結や行動阻害を引き起こす。",
    playableInMvp: true,
  },
  {
    id: "typhoon",
    index: "07",
    name: "台風",
    maxHp: 1100,
    color: "#314d65",
    accentColor: "#24d8ff",
    coreColor: "#f9fbff",
    icon: "◎",
    trait: "Coming soon",
    threat: 9,
    difficulty: 5,
    description: "豪雨・落雷・竜巻の複合型。現在は調整中。",
    playableInMvp: false,
  },
];

export const weapons: Weapon[] = [
  {
    id: "weatherGun",
    name: "ウェザーガン",
    damage: 11,
    maxAmmo: 32,
    fireRateMs: 90,
    skillName: "天候連射",
    skillDescription: "短時間で連射力が上がり、敵HPを段階的に削る",
    skillBurstRatio: 0.18,
    skillBurstShots: 8,
    description: "標準装備。連射力に優れた基本武器。",
    specialtyAgainst: [],
    specialtyMultiplier: 1,
  },
  {
    id: "clearSkyGun",
    name: "クリアスカイガン",
    damage: 17,
    maxAmmo: 22,
    fireRateMs: 140,
    skillName: "晴天バースト",
    skillDescription: "高威力の単発バーストを撃ち込む",
    skillBurstRatio: 0.32,
    skillBurstShots: 5,
    description: "バランス型。武器スキルが扱いやすい。",
    specialtyAgainst: [],
    specialtyMultiplier: 1,
  },
  {
    id: "rainySeasonKiller",
    name: "梅雨キラー",
    damage: 28,
    maxAmmo: 9,
    fireRateMs: 220,
    skillName: "湿度排除",
    skillDescription: "湿度系の敵に追加ダメージを与える",
    skillBurstRatio: 0.42,
    skillBurstShots: 3,
    description: "高威力低連射。湿度系の敵への特効。",
    specialtyAgainst: ["rainySeason", "heavyRain"],
    specialtyMultiplier: 1.45,
  },
  {
    id: "stormwallRifle",
    name: "雷除けライフル",
    damage: 16,
    maxAmmo: 14,
    fireRateMs: 130,
    skillName: "電界反射",
    skillDescription: "対落雷で追加ダメージ。短時間スキル中の被ダメ軽減",
    skillBurstRatio: 0.28,
    skillBurstShots: 4,
    description: "対落雷特化。電界を編んで雷を逸らす。",
    specialtyAgainst: ["thunderstorm"],
    specialtyMultiplier: 1.55,
  },
  {
    id: "frostlance",
    name: "凍結カノン",
    damage: 24,
    maxAmmo: 10,
    fireRateMs: 200,
    skillName: "凍結弾",
    skillDescription: "吹雪/竜巻系を凍結し、追加ダメージ",
    skillBurstRatio: 0.36,
    skillBurstShots: 4,
    description: "対吹雪・竜巻特化。冷気で天候を抑え込む。",
    specialtyAgainst: ["blizzard", "tornado"],
    specialtyMultiplier: 1.4,
  },
  {
    id: "windBlade",
    name: "風向ブレード",
    damage: 36,
    maxAmmo: 6,
    fireRateMs: 260,
    skillName: "風向反転",
    skillDescription: "近接斬撃の気圧刃で竜巻の向きをそらし、竜巻/台風に追加ダメージ",
    skillBurstRatio: 0.46,
    skillBurstShots: 3,
    description: "風向を斬って乱流を逸らす近接型ブレード。弾数は少ないが一撃が重い。",
    specialtyAgainst: ["tornado", "typhoon"],
    specialtyMultiplier: 1.5,
  },
];

export const items: Item[] = [
  {
    id: "clearTonic",
    slotKey: "1",
    name: "晴れ薬",
    effect: "耐候値を回復",
    description: "使用すると耐候値を 350 回復する",
    initialStock: 3,
  },
  {
    id: "lightningRod",
    slotKey: "2",
    name: "避雷針",
    effect: "落雷予兆を打ち消す",
    description: "場のすべての落雷予兆を消す",
    initialStock: 2,
  },
  {
    id: "decoyUmbrella",
    slotKey: "3",
    name: "デコイ傘",
    effect: "敵の狙いを逸らす",
    description: "5秒間、被ダメージを 60% 軽減する",
    initialStock: 2,
  },
  {
    id: "pressureStabilizer",
    slotKey: "4",
    name: "気圧安定剤",
    effect: "気圧ゲージを蓄積",
    description: "武器スキルゲージを大きく増やす",
    initialStock: 1,
  },
];

export const characters: Character[] = [
  {
    id: "noa",
    codename: "ノア",
    callSign: "NOA",
    role: "バランス",
    passiveName: "晴天適応",
    passiveDescription: "命中時の与ダメージ +10%",
    damageMultiplier: 1.1,
    damageTakenMultiplier: 1.0,
    gaugeGainMultiplier: 1.0,
    accentColor: "#28d9ff",
    description: "気象観測局所属の青年パイロット。父を長雨で亡くしてから、空を晴らすことを生涯の課題に決めた。",
    flavor: "梅雨だけは許さない。",
  },
  {
    id: "saka",
    codename: "サカ",
    callSign: "SAKA",
    role: "攻撃",
    passiveName: "気圧収束",
    passiveDescription: "気圧ゲージ +30% / 被ダメージ +10%",
    damageMultiplier: 1.0,
    damageTakenMultiplier: 1.1,
    gaugeGainMultiplier: 1.3,
    accentColor: "#ffd84d",
    description: "気圧操作を専門とする若手アタッカー。短期決戦と派手な火力を好む。",
    flavor: "雷一発で、空に風穴開けてやる。",
  },
];

export const stages: Stage[] = [
  {
    id: "lab",
    name: "実験場",
    description: "試作機の検証場。整備された円形フィールド。",
    ambientColor: "#1f4255",
    groundColor: "#0a141c",
    ringColor: "#28d9ff",
    fogColor: "#06121b",
    skyTurbidity: 9,
    skyRayleigh: 3.2,
    buildingColor: "#1f2f3a",
    buildingEmissive: "#0aa0d7",
    arena: { x: 11, zFront: -3, zBack: 9 },
  },
  {
    id: "ruins",
    name: "都市跡",
    description: "崩壊した観測都市。瓦礫が残る非対称地形。",
    ambientColor: "#3d2218",
    groundColor: "#1a0f0a",
    ringColor: "#ff8845",
    fogColor: "#1a0c08",
    skyTurbidity: 14,
    skyRayleigh: 1.4,
    buildingColor: "#3a2a26",
    buildingEmissive: "#d76a2e",
    arena: { x: 19, zFront: -6, zBack: 16 },
  },
  {
    id: "highland",
    name: "高地観測所",
    description: "極寒の山頂観測所。視界が霧で淡い。",
    ambientColor: "#22425b",
    groundColor: "#152030",
    ringColor: "#bce6ff",
    fogColor: "#a7c8d8",
    skyTurbidity: 4,
    skyRayleigh: 0.8,
    buildingColor: "#2c4453",
    buildingEmissive: "#7ab5d7",
    arena: { x: 21, zFront: -7, zBack: 18 },
  },
];

type DifficultyModifier = {
  hp: number;
  attackDamage: number;
  attackInterval: number;
  itemMultiplier: number;
  movementAggression: number;
};

export const difficultyModifiers: Record<1 | 2 | 3 | 4 | 5, DifficultyModifier> = {
  1: { hp: 0.7, attackDamage: 0.55, attackInterval: 1.6, itemMultiplier: 1.6, movementAggression: 0.5 },
  2: { hp: 0.9, attackDamage: 0.85, attackInterval: 1.25, itemMultiplier: 1.3, movementAggression: 0.75 },
  3: { hp: 1.0, attackDamage: 1.0, attackInterval: 1.0, itemMultiplier: 1.0, movementAggression: 1.0 },
  4: { hp: 1.25, attackDamage: 1.25, attackInterval: 0.82, itemMultiplier: 0.7, movementAggression: 1.3 },
  5: { hp: 1.6, attackDamage: 1.55, attackInterval: 0.65, itemMultiplier: 0.5, movementAggression: 1.7 },
};

export type EnemyAttackPattern = {
  intervalMs: number;
  warningMs: number;
  damage: number;
  radius: number;
  projectileColor: string;
  arcHeight: number;
  spreadX: number;
  spreadZ: number;
  followsPlayer: boolean;
  trailGlow: number;
  kind: "arc" | "linear" | "falling";
  knockback: number;
  barrierIntervalMs: number;
  barrierDurationMs: number;
};

export const enemyAttackPatterns: Record<string, EnemyAttackPattern> = {
  cloudy: {
    intervalMs: 4500,
    warningMs: 1800,
    damage: 24,
    radius: 1.6,
    projectileColor: "#cfe9f4",
    arcHeight: 3.6,
    spreadX: 8,
    spreadZ: 6,
    followsPlayer: false,
    trailGlow: 0.6,
    kind: "arc",
    knockback: 0,
    barrierIntervalMs: 0,
    barrierDurationMs: 0,
  },
  heavyRain: {
    intervalMs: 1100,
    warningMs: 700,
    damage: 30,
    radius: 1.4,
    projectileColor: "#5ee7ff",
    arcHeight: 0,
    spreadX: 12,
    spreadZ: 8,
    followsPlayer: true,
    trailGlow: 1.4,
    kind: "linear",
    knockback: 0.6,
    barrierIntervalMs: 0,
    barrierDurationMs: 0,
  },
  thunderstorm: {
    intervalMs: 2200,
    warningMs: 1500,
    damage: 95,
    radius: 1.6,
    projectileColor: "#fff2a6",
    arcHeight: 0,
    spreadX: 14,
    spreadZ: 9,
    followsPlayer: false,
    trailGlow: 2.4,
    kind: "falling",
    knockback: 0.4,
    barrierIntervalMs: 17000,
    barrierDurationMs: 1800,
  },
  tornado: {
    intervalMs: 1700,
    warningMs: 1100,
    damage: 60,
    radius: 1.5,
    projectileColor: "#8df0ff",
    arcHeight: 2.4,
    spreadX: 5,
    spreadZ: 4,
    followsPlayer: true,
    trailGlow: 1.4,
    kind: "arc",
    knockback: 1.6,
    barrierIntervalMs: 0,
    barrierDurationMs: 0,
  },
  rainySeason: {
    intervalMs: 2900,
    warningMs: 1700,
    damage: 64,
    radius: 2.1,
    projectileColor: "#8dffd8",
    arcHeight: 3.4,
    spreadX: 10,
    spreadZ: 7,
    followsPlayer: false,
    trailGlow: 1.0,
    kind: "arc",
    knockback: 0.3,
    barrierIntervalMs: 0,
    barrierDurationMs: 0,
  },
  blizzard: {
    intervalMs: 2500,
    warningMs: 1400,
    damage: 72,
    radius: 1.7,
    projectileColor: "#dff8ff",
    arcHeight: 3.0,
    spreadX: 12,
    spreadZ: 8,
    followsPlayer: false,
    trailGlow: 1.6,
    kind: "arc",
    knockback: 0.8,
    barrierIntervalMs: 0,
    barrierDurationMs: 0,
  },
  typhoon: {
    intervalMs: 1500,
    warningMs: 1000,
    damage: 96,
    radius: 2.0,
    projectileColor: "#f9fbff",
    arcHeight: 0,
    spreadX: 16,
    spreadZ: 10,
    followsPlayer: true,
    trailGlow: 2.2,
    kind: "linear",
    knockback: 1.4,
    barrierIntervalMs: 14000,
    barrierDurationMs: 2400,
  },
};

export const initialWeapon: Weapon = weapons[1];

export const findWeapon = (id: Weapon["id"]) =>
  weapons.find((weapon) => weapon.id === id) ?? initialWeapon;

export const findItem = (id: Item["id"]) =>
  items.find((item) => item.id === id);

export const findCharacter = (id: Character["id"]) =>
  characters.find((character) => character.id === id) ?? characters[0];

export const findStage = (id: Stage["id"]) =>
  stages.find((stage) => stage.id === id) ?? stages[0];

export const mvpEnemies = weatherEnemies.filter((enemy) => enemy.playableInMvp);
