import type { WeatherEnemy, Weapon } from "./types";

export const weatherEnemies: WeatherEnemy[] = [
  {
    id: "cloudy",
    index: "01",
    name: "曇り",
    maxHp: 80,
    color: "#b9c2c9",
    accentColor: "#63d8ff",
    coreColor: "#b7f2ff",
    icon: "☁",
    trait: "練習",
    threat: 2,
    description: "チュートリアル用の練習エネミー。視界を少し曇らせる。",
    playableInMvp: true,
  },
  {
    id: "heavyRain",
    index: "02",
    name: "豪雨",
    maxHp: 120,
    color: "#255f88",
    accentColor: "#29c8ff",
    coreColor: "#5ee7ff",
    icon: "☔",
    trait: "視界妨害",
    threat: 4,
    description: "強い雨で視界を妨げ、継続ダメージを与える。",
    playableInMvp: true,
  },
  {
    id: "thunderstorm",
    index: "03",
    name: "多雷",
    maxHp: 140,
    color: "#4b4f58",
    accentColor: "#ffd84d",
    coreColor: "#fff2a6",
    icon: "⚡",
    trait: "落雷",
    threat: 6,
    description: "周囲に落雷を発生させ、広範囲に高ダメージ。",
    playableInMvp: true,
  },
  {
    id: "tornado",
    index: "04",
    name: "竜巻",
    maxHp: 160,
    color: "#9fb8c8",
    accentColor: "#6be6ff",
    coreColor: "#8df0ff",
    icon: "◌",
    trait: "吸引",
    threat: 7,
    description: "プレイヤーを吸引し、接近して連続攻撃を行う。",
    playableInMvp: false,
  },
  {
    id: "rainySeason",
    index: "05",
    name: "梅雨",
    maxHp: 180,
    color: "#315d54",
    accentColor: "#4ce0b3",
    coreColor: "#8dffd8",
    icon: "♢",
    trait: "状態異常",
    threat: 7,
    description: "湿気をまとい、継続ダメージや移動速度低下を付与。",
    playableInMvp: false,
  },
  {
    id: "blizzard",
    index: "06",
    name: "吹雪",
    maxHp: 170,
    color: "#b7d7f2",
    accentColor: "#9fe8ff",
    coreColor: "#dff8ff",
    icon: "❄",
    trait: "凍結",
    threat: 6,
    description: "吹雪を起こし、氷結や行動阻害を引き起こす。",
    playableInMvp: false,
  },
  {
    id: "typhoon",
    index: "07",
    name: "台風",
    maxHp: 260,
    color: "#314d65",
    accentColor: "#24d8ff",
    coreColor: "#f9fbff",
    icon: "◎",
    trait: "複合型",
    threat: 9,
    description: "豪雨・多雷・竜巻の複合型。将来的な大型ボス候補。",
    playableInMvp: false,
  },
];

export const initialWeapon: Weapon = {
  name: "クリアスカイガン",
  damage: 12,
  maxAmmo: 120,
  skillName: "晴天バースト",
};

export const mvpEnemies = weatherEnemies.filter((enemy) => enemy.playableInMvp);
